apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: backend
  type: ClusterIP