apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: database
  type: ClusterIP