name: Java CI
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: go test ./frontend/
  Docker-image:
      runs-on: ubuntu-latest
      needs: Test
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: build docker backend
          run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/build-backend-docker.sh
        - name: push docker backend
          run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/push-backend-docker.sh
        - name: build docker frontend
          run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/build-frontend-docker.sh
        - name: push docker frontend
          run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/push-frontend-docker.sh
  Run-on-server:
      runs-on: self-hosted
      needs: Docker-image
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: run compose
          run: bash ci/composeup.sh
  
